1. What does Pandas stand for?

    1. **Panel Data**
    2. **Python Data Analysis**
2. What are the 2 collections used in Pandas?

    1. **Series**
    2. **Dataframe**

3. Name 4 things Pandas can do for us.

    1. **load**
    2. **manipulate**
    3. **prepare**
    4. **analyze**

4. To permanently sort a DataFrame, which keyword should one use with the `df.sort()` method?

**True**

5. What is a CSV?

**Comma Separated Values (files)**

6. When cleaning data what values do we not like in our data?

**NULL Values**



In [2]:
#7. Import NumPy, use one of the NumPy methods and create an array with a shape of (2, 3, 2). You can use the reshape method -- `.reshape()`

import numpy as np



array1 = np.arange(12)
array1.reshape(2, 3, 2)

#8. Use NumPy `.linspace()` to create an array with 6 linearly spaced values between 0 and 20


array2 = np.linspace(0,20,6)
array2

#9. Make a Deep Copy of the above array

import copy

array3 = copy.deepcopy(array2)
array3

import numpy as np

arrayA = [[25, 16]]
arrayB = [[11, 2], [13, 4]]
arrayC = [[7, 81], [5, 6], [11, 12]]

# Concatenate arrays along axis 0
newArray = np.concatenate((arrayA, arrayB, arrayC), axis=0)

# Sort the array
sortedArray = np.sort(newArray)

# Print the sorted array
print(sortedArray)


[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]


In [17]:
#10. Concatenate these 3 arrays into a new array named 'newArray'...
#    ```python
#            ([[25, 16]])
#            ([[11, 2], [13, 4]])
#            ([[7, 81], [5, 6], [11, 12]])
#  ``

arrayA = ([[25, 16]])
arrayB = ([[11, 2], [13, 4]])
arrayC = ([[7, 81], [5, 6], [11, 12]])

newArray = np.concatenate((arrayA, arrayB, arrayC), axis = 0)

newArray

#11. Sort 'newArray' in order into 'sortedArray'

sortedArray = np.sort(newArray)
print(np.sort(sortedArray))

#12. Unpack the array tuples from the above 'reshapedArray'  into 4 well named variables. Print the 4 variables.
#Removed

#13. Combined and sort the following arrays into one called 'comboArray' ...

#   ```python
#       one = ([10, 11, 12, 13, 14, 15, 16, 17])
#       two = ([20, 21, 22, 23, 24, 25, 26, 27])
#       three = ([ 0, 1, 2, 3, 4, 5, 6, 7])

arrayD = np.array([10, 11, 12, 13, 14, 15, 16, 17])
arrayE = np.array([20, 21, 22, 23, 24, 25, 26, 27])
arrayF = np.array([0, 1, 2, 3, 4, 5, 6, 7])
comboArray = np.sort(np.concatenate((arrayD, arrayE, arrayF)))
print(comboArray)

#14. Take 'comboArray' and perform the following slicing activities:

#    - print sec1 - the 2nd element
#    - print sec2 - all elements from the 3rd element to the last
#    - print sec3 - all elements from the 4th to the 14th elements
#    - print sec4 - the last 6 elements
#    - print sec5 - all element from #0 up to and including #15, using the negative number method, i.e. taking a section from the end.
#    - print sec6 - from #20 every even element to the end
#    - print sec7 - from the last element moving forward, every 5th element.

print("The 2nd element:", comboArray[1])
print("All elements from the 3rd to the last:", comboArray[2:])
print("All elements from the 4th to the 14th:", comboArray[3:14])
print("The last 6 elements:", comboArray[-6:])
print("All the elements from #0 up to and including #15:", comboArray[:-10])
print("Every even element from #20 to the end:", comboArray[-8::2])
print("From the last element moving forward, every 5th:", comboArray[0:-1:5])

#15. Using `Series`, create a `DataFrame` that looks like this:

#    | Ingredients | Quantity | Unit |
#    |----|----|----|
#    | Flour | 4 | cups |
#    | Milk | 1 | cup |
#    | Eggs | 2 | large |
#    | Spam | 1 | can |

#    Name: Dinner, dtype: object

import pandas

names = pandas.Series(['Flour', 'Milk', 'Eggs', 'Spam'], name='ingredients')
amounts = pandas.Series([4, 1, 2, 1], name='quantity')

df = pandas.DataFrame(names).join(amounts)

df

import pandas

names = pandas.Series(['Flour', 'Milk', 'Eggs', 'Spam'])
amounts = pandas.Series([4, 1, 2, 1])

df = pandas.DataFrame({
    'ingredient': names,
    'quantity': amounts
})

df

#16. Take this data and create a DataFrame named studentData
#    ```Python
#        {'Name': ['Jai', 'janusha', 'Gaurav', 'Anuj'],
#            'Height': [5.1, 6.2, 5.1, 5.2],
#            'Qualification': ['Msc', 'MA', 'Msc', 'Msc'],
#            'address': ['Delhi', 'Doha', 'Chennai', 'Dakhar'],
#            'Age': [21, 23, 24, 21],
#            'Pets': ['Dog', 'Bunny', 'Chinchilla', 'Parrot'],
#            'sport': ['Darts', 'Basketball', 'PaddleBoarding', 'Cricket']
#        }
#    ```

import pandas as pd 
name = pd.Series(['Jai', 'janusha', 'Gaurav', 'Anuj'], name = 'Name')
height = pd.Series([5.1, 6.2, 5.1, 5.2], name = "Height")
qualification = pd.Series(['Msc', 'MA', 'Msc', 'Msc'], name ='Qualification')
address = pd.Series(['Delhi', 'Doha', 'Chennai', 'Dakar'], name ='Address')
pet = pd.Series(['Dog', 'Bunny', 'Chinchilla', 'Parrot'], name ='Pets')
sport = pd.Series(['Darts', 'Basketball', 'Paddleboarding', "Cricket"], name = 'Sport')
studentData = pd.concat([name, height, qualification, address, pet, sport], axis=1)


#17. Add a new column to the DataFrame with the following deserts:
#        ["ice cream", "Cashew Fudge", "waffels", "Carrot Halwa"]


dessert = pd.Series(['Ice Cream', 'Cashew Fudge', 'Waffles', 'Carrot Halwa'], name = 'Dessert')
studentData = pd.DataFrame(studentData).join(dessert)



#18. Sort the 'studentData' DataFrame in Ascending order -- Sorting by column 'Name' and then "address"

studentData.sort_values(by = ['Name', 'Address'], inplace = True)
print(studentData)

#19. Save this `DataFrame` here below to disc as a `.CSV` file with the name `cows_and_goats.csv`:
#    ```python
#        df = pd.DataFrame({'Cows': [12, 20], 'Goats': [22, 19]}, index=['Year 1', 'Year 2'])

df = pd.DataFrame({'Cows': [12,20], 'Goats': [22,19]}, index=['Year 1', 'Year 2'])
df.to_csv('cows_and_goats.csv')

#20. (A) Using Pandas, make your own .CSV file with data on vegetables and save it. (B) Using Pandas, make a change to your CSV file, and save a copy with a different name.

greatVegetable = pd.Series(['Carrot', 'Spinach','Peas','Parsnip'], name='Delicious Vegetables')
goodVegetable = pd.Series(['Cauliflower', 'Leek', 'Kale', 'Cucumber'], name='Okay Vegetables')
badVegetable = pd.Series(['Carrot', 'Artichoke', 'Corn', 'Okra'], name='Nasty Vegetables')


vegetableData= pd.concat([greatVegetable, goodVegetable, badVegetable], axis=1)
vegetableData.to_csv('Vegetables.csv')

numberTwo = pd.Series(['Swiss Chard', 'Collard Greens', 'Celery'])
vegetableData2 = pd.concat([vegetableData, numberTwo.to_frame().T])
vegetableData2.to_csv('Vegetables2.csv')
vegetableData2

[[16 25]
 [ 2 11]
 [ 4 13]
 [ 7 81]
 [ 5  6]
 [11 12]]
[ 0  1  2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
The 2nd element: 1
All elements from the 3rd to the last: [ 2  3  4  5  6  7 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27]
All elements from the 4th to the 14th: [ 3  4  5  6  7 10 11 12 13 14 15]
The last 6 elements: [22 23 24 25 26 27]
All the elements from #0 up to and including #15: [ 0  1  2  3  4  5  6  7 10 11 12 13 14 15]
Every even element from #20 to the end: [20 22 24 26]
From the last element moving forward, every 5th: [ 0  5 12 17 24]
      Name  Height Qualification  Address        Pets           Sport  \
3     Anuj     5.2           Msc    Dakar      Parrot         Cricket   
2   Gaurav     5.1           Msc  Chennai  Chinchilla  Paddleboarding   
0      Jai     5.1           Msc    Delhi         Dog           Darts   
1  janusha     6.2            MA     Doha       Bunny      Basketball   

        Dessert  
3  Carrot Halwa  
2       Waffle

Delicious Vegetables Okay Vegetables Nasty Vegetables            0  \
0               Carrot     Cauliflower           Carrot          NaN   
1              Spinach            Leek        Artichoke          NaN   
2                 Peas            Kale             Corn          NaN   
3              Parsnip        Cucumber             Okra          NaN   
0                  NaN             NaN              NaN  Swiss Chard   

                1       2  
0             NaN     NaN  
1             NaN     NaN  
2             NaN     NaN  
3             NaN     NaN  
0  Collard Greens  Celery